server:
  port: 9002

member-service:
  url: http://localhost:9002

comatching:
  profile:
    default-images:
      base-url: "https://${AWS_S3_BUCKET}.s3.ap-northeast-2.amazonaws.com/defaults/profile/"
      filenames:
        - "userDefaultImage1.jpg"
        - "userDefaultImage2.jpg"
        - "userDefaultImage3.jpg"

spring:
  application:
    name: member-service

  datasource:
    url: jdbc:mysql://localhost:3307/comatching_member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:comatching12!@}
    hikari:
      pool-name: HikariPool-${spring.application.name}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: member-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: ${ACCESS_TOKEN_EXP:86400000}
  refresh-token:
    expiration: ${REFRESH_TOKEN_EXP:604800000}
