server:
  port: 9006

member-service:
  url: http://localhost:9002

spring:
  application:
    name: item-service

  config:
    import: optional:classpath:application-secret.yml

  datasource:
    url: jdbc:mysql://localhost:3307/comatching_item?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    hikari:
      pool-name: HikariPool-${spring.application.name}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: item-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer